# Data Homework: Chapter 5

Name:<u> Enter your full name here

Directions: Download the following data in from [FRED] (https://fred.stlouisfed.org/graph/?g=pUAe) using pandas_datareader
 
>GDP Deflator: GDPDEF
>
>Monetary Base: BOGMBASEW

1.	Calculate the real base money stock (M/P) using data for the GDP Deflator and the Monetary Base. Make sure to reindex the price level by dividing it by 100.

$(1/1/100) --> 1 * 100$

In [2]:
#plots.py
# if you have not installed pandas-datareader, uncomment the command 
# in the next line. After intallation, you can remove the command
#!pip install pandas-datareader
# pandas_datareader is imported in datlib.FRED
import datetime
from datlib.FRED import *
# for each variable, enter the variable name followed by the variable code. 
# the first variable is completed for you
data_codes  = {"GDP Deflator":"GDPDEF",
              "Monetary Base": "BOGMBASEW"}
# Select start and end dates
# datetime.datetime(year, month, day)
start = datetime.datetime(1990, 1, 1)
end = datetime.datetime.today()
data = gather_data(data_codes = data_codes, 
                   start = start, 
                   end = end, 
                   freq = "Q")
data

            GDP Deflator  Monetary Base
DATE
1990-03-31        62.754   2.914552e+05
1990-06-30        63.457   2.984113e+05
1990-09-30        64.001   3.055920e+05
1990-12-31        64.477   3.121394e+05
1991-03-31        65.109   3.095298e+05
1991-06-30        65.587   3.150710e+05
1991-09-30        66.099   3.206633e+05
1991-12-31        66.492   3.277948e+05
1992-03-31        66.739   3.336175e+05
1992-06-30        67.140   3.347158e+05
1992-09-30        67.468   3.430106e+05
1992-12-31        67.932   3.557535e+05
1993-03-31        68.313   3.610851e+05
1993-06-30        68.719   3.718342e+05
1993-09-30        69.128   3.814728e+05
1993-12-31        69.505   3.926674e+05
1994-03-31        69.837   3.988637e+05
1994-06-30        70.174   4.084489e+05
1994-09-30        70.577   4.156268e+05
1994-12-31        70.960   4.229724e+05
1995-03-31        71.344   4.258295e+05
1995-06-30        71.687   4.340561e+05
1995-09-30        72.040   4.358959e+05
1995-12-31        72.387   4.399032e+05
1996-03-31        72.736   4.397288e+05
1996-06-30        73.037   4.440598e+05
1996-09-30        73.276   4.507555e+05
1996-12-31        73.668   4.570257e+05
1997-03-31        74.107   4.619417e+05
1997-06-30        74.257   4.671093e+05
...                  ...            ...
2013-09-30       101.918   3.378793e+06
2013-12-31       102.517   3.655391e+06
2014-03-31       102.937   3.801888e+06
2014-06-30       103.512   3.928910e+06
2014-09-30       103.957   4.031295e+06
2014-12-31       104.123   3.928296e+06
2015-03-31       104.031   3.961301e+06
2015-06-30       104.596   3.986968e+06
2015-09-30       104.926   3.983751e+06
2015-12-31       104.937   3.970862e+06
2016-03-31       104.865   3.851397e+06
2016-06-30       105.592   3.846764e+06
2016-09-30       105.950   3.780016e+06
2016-12-31       106.469   3.582060e+06
2017-03-31       107.010   3.719278e+06
2017-06-30       107.340   3.789588e+06
2017-09-30       107.872   3.858169e+06
2017-12-31       108.598   3.865413e+06
2018-03-31       109.237   3.824687e+06
2018-06-30       110.176   3.688997e+06
2018-09-30       110.614   3.590916e+06
2018-12-31       111.140   3.474326e+06
2019-03-31       111.424   3.361417e+06
2019-06-30       112.141   3.273692e+06
2019-09-30       112.531   3.243848e+06
2019-12-31       112.950   3.320522e+06
2020-03-31       113.415   3.524601e+06
2020-06-30       112.817   4.978059e+06
2020-09-30       113.840   4.776974e+06
2020-12-31       114.373            NaN

[124 rows x 2 columns]

In [3]:
data["Real Monetary Base"] = data["Monetary Base"].div(data["GDP Deflator"].div(100))

2.	Log the values of the Monetary Base and the Real Monetary Base

3.	Calculate the First Difference (log(xt) – log(x t-1) of Logged Values for the Monetary Base and Real Monetary Base

4.	Plot the observed and the logged values for each variable on a single graph. Use a second y-axis for the logged values.

5.	Graph the differenced logged values of both the Monetary Base and the Real Monetary Base on a single graph.

6.	What does the slope of logged data approximate?

7.	What does the difference of logged values represent?

8.	What is the advantage of using logged values compared to using non-logged values for visualizing macroeconomic data?