# Data Homework: Chapter 3

Name:<u> James Caton

Download the following data:

>Global Price of Brent Crude (U.S. Dollars per Pound): POILBREUSDQ
>
>Global Price of Bananas (U.S. Dollars per Pound): PBANSOPUSDQ
>
>Global Price of Orange (U.S. Dollars per Pound): PORANGUSDM
>
>CPI â€“ Total All Items for the United States: CPALTT01USM661S

In [6]:
#plots.py
# if you have not installed pandas-datareader, uncomment the command 
# in the next line. After intallation, you can remove the command
#!pip install pandas-datareader
# pandas_datareader is imported in datlib.FRED
import datetime
from datlib.FRED import *
# for each variable, enter the variable name followed by the variable code. 
# the first variable is completed for you
data_codes  = {"Brent Crude Oil Price":"POILBREUSDQ",
               "Bananas Price":"PBANSOPUSDQ",
               "Global Price of Oranges":"PORANGUSDM",
              "CPI": "CPALTT01USM661S"}
# Select start and end dates
# datetime.datetime(year, month, day)
start = datetime.datetime(1990, 1, 1)
end = datetime.datetime.today()

In [8]:
data = gather_data(data_codes = data_codes, 
                   start = start, 
                   end = end, 
                   freq = "Q")

In [9]:
data

,Brent Crude Oil Price,Bananas Price,Global Price of Oranges,CPI
DATE,,,,
1990-03-31,19.850000,591.033333,1.925521,54.018629
1990-06-30,15.960000,535.900000,1.924709,54.553049
1990-09-30,26.496667,565.200000,1.667892,55.495316
1990-12-31,32.536667,471.266667,1.149757,56.437583
1991-03-31,20.750000,709.230000,1.171534,56.859494
1991-06-30,18.790000,681.863333,1.168999,57.197022
1991-09-30,19.876667,415.753333,1.191080,57.632997
1991-12-31,20.510000,431.000000,1.600363,58.111162
1992-03-31,18.206667,594.100000,1.449386,58.504945
1992-06-30,20.123333,416.423333,1.335894,58.954984
1992-09-30,20.140000,521.650000,1.163217,59.405022
1992-12-31,19.186667,360.160000,0.970681,59.925378
1993-03-31,18.193333,589.843333,0.755782,60.361352
1993-06-30,18.243333,471.620000,1.019888,60.797327
1993-09-30,16.486667,339.466667,1.200926,61.078601
1993-12-31,15.066667,371.173333,1.100549,61.584893
1994-03-31,13.950000,568.386667,1.078939,61.894295
1994-06-30,16.050000,374.106667,0.970364,62.245887
1994-09-30,16.766667,430.653333,0.914515,62.822498
1994-12-31,16.536667,386.016667,1.067736,63.188154
1995-03-31,16.903333,445.376667,1.023310,63.652256
1995-06-30,18.136667,382.570000,1.041882,64.172612
1995-09-30,16.196667,525.136667,1.048077,64.496077
1995-12-31,16.986667,427.326667,1.200514,64.847669
1996-03-31,18.633333,501.403333,1.249326,65.424280
1996-06-30,19.476667,541.823333,1.258165,65.986828
1996-09-30,20.543333,409.030000,1.146155,66.366548
1996-12-31,23.160000,426.080000,1.005980,66.943159
1997-03-31,21.170000,740.791897,0.819333,67.351006
1997-06-30,18.053333,497.007366,0.765702,67.505706
...,...,...,...,...
2013-06-30,103.004137,910.610428,1.447986,97.902260
2013-09-30,110.100839,934.203918,1.363098,98.431758
2013-12-31,109.396478,928.121509,1.321633,98.795726
2014-03-31,107.929383,947.133477,1.469657,99.411013
2014-06-30,109.806645,929.191281,1.585698,99.938964
2014-09-30,102.080596,939.274180,1.463368,100.194641
2014-12-31,75.956870,911.902474,1.398488,99.945714
2015-03-31,54.046227,974.803281,1.320471,99.298784
2015-06-30,62.098961,978.370923,1.166227,99.975951
2015-09-30,50.031494,948.921631,1.232768,100.353561
2015-12-31,43.420991,932.738992,1.385010,100.345967
2016-03-31,34.357723,1028.166691,1.297217,100.320652
2016-06-30,45.952843,992.960385,1.483365,101.036213
2016-09-30,45.801312,1023.168354,1.877982,101.508049
2016-12-31,50.078218,965.425765,2.073754,102.151041
2017-03-31,54.118163,1029.792017,1.745434,102.871102
2017-06-30,50.276305,1081.551766,1.470804,102.969126
2017-09-30,51.740807,1098.066298,1.387371,103.519579
2017-12-31,61.468362,1087.492925,1.546967,104.317412
2018-03-31,66.951325,1185.778394,1.428570,105.154764
2018-06-30,74.488668,1155.697967,1.562870,105.727015
2018-09-30,75.475474,1121.418667,1.596555,106.271983
2018-12-31,67.369294,1128.102254,1.384909,106.615700
2019-03-31,63.272520,1156.099272,1.202325,106.859564
2019-06-30,68.339780,1142.432613,1.032551,107.659226
2019-09-30,61.859091,1134.898711,1.004858,108.146110
2019-12-31,62.656277,1136.409131,0.980625,108.782211
2020-03-31,50.529164,1185.597872,1.005241,109.109333
2020-06-30,31.429769,1291.007948,1.182359,108.133453
2020-09-30,42.718692,1252.543797,1.185122,109.501709

1. Create line graphs reflecting the prices of each commodity over time.

In [ ]:
# you will need to use functions from the datlib folder. 
# Reference the Data Homework Guide if you are unfamiliar with this
from datlib.plots import *

2. The real price of commodity $i$ is calculated as $\frac{p_i}{P}$, the price of good $i$ divided by the price level. Calculate the real price of each good using $CPI$ as the price level, $P$.

In [ ]:
#Hint: Use data[real_name] = data[name].div(data["CPI"])

3. Create a separate graph of the real price for each good $i$.

4. Have goods tended to become more or less expensive in real terms? Why do you think this is?